# ESP8266 nodeMCU
esphome:
  name: sensor-th-2

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

# Enable Logging
logger:

# Enable home assistant API
api:

ota:

web_server:
  port: 80

prometheus:

# https://esphome.io/components/wifi.html
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 172.16.40.52
    gateway: 172.16.40.254
    subnet: 255.255.255.0
    dns1: 172.16.1.10
    dns2: 172.16.1.11

# https://esphome.io/components/i2c.html#i2c
i2c:
  - id: bus_a
    sda: D1
    scl: D2
    scan: true

# https://esphome.io/components/sensor/sht3xd.html
sensor:
  - platform: sht3xd
    temperature:
      name: "Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Humidity"
    address: 0x44
    update_interval: 15s
